### ISSUE TITLE
Woodworking Guild Merchant not selling anything

### ISSUE THREAD

**Issue by Totemics** [OmegaPrivateServer/issues#26] opened 2019-12-04 21:15 UTC
Chaupire (https://ffxiclopedia.fandom.com/wiki/Chaupire) is the Woodworking Guild Merchant and is not selling any items.

## Expected Behavior
Chaupire should sell certain items, listed in the Wiki

## Current Behavior
When clicking on him, the merchant options 'Buy' and 'Sell' pop up like normal but when selecting 'Buy', there is a denial sound and nothing happens. After some time, clicking on 'Buy' will open a blank window with no items to buy. 

## Steps to Reproduce

1. I tried this on Earthsday, the shop is closed on Firesday (and was closed when I checked, like normal)
2.
3.
4.

**Comment by OmegaBison** [comment] 2019-12-04 21:17
That's normal. Those guild merchants are stocked by players. They won't sell anything unless players sell to them first.

**Comment by Totemics** [comment] 2019-12-04 21:56
Sorry, you're mistaken. They sell certain items in addition to player-stocked items. Here is another resource: https://www.bg-wiki.com/bg/Chaupire

Compare it to another Guild Merchant who works the exact same way: https://www.bg-wiki.com/bg/Doggomehr
This one is selling items properly. Again, when trying to click 'Buy' from Chaupire, there is an error sound and nothing happens, but if you keep trying then a blank window opens up. It's a bug.

**Comment by OmegaBison** [comment] 2019-12-09 22:41
Are you sure about that? DSP team has also previously confirmed that this is intended behavior for this shop. See this thread from December 2018: https://github.com/DarkstarProject/darkstar/issues/5443

**Comment by OmegaBison** [comment] 2019-12-16 14:05
Closing this ticket until we get some more feedback about whether the current implementation is correct or not.

**Closed as completed by OmegaBison** 2019-12-16 14:05 UTC
