### ISSUE TITLE
Thunder elementals in Konschtat Highlands deaggro while fighting them

### ISSUE THREAD

**Issue by dvalderrama89** [OmegaPrivateServer/issues#31] opened 2019-12-07 05:50 UTC
Please view this stream clip for evidence. The elemental deaggros 2 times total - once while I am in the middle of fighting it the ele deaggros while lightning weather is still active, then again after lightning weather is not active. The 2nd time the ele depops because weather is over.

https://clips.twitch.tv/HomelyDirtySwanOSsloth

## Expected Behavior

The elemental should stay claimed to the player throughout the entire fight.
## Current Behavior

The elemental deaggrod midway through the fight multiple times.

## Steps to Reproduce
1. Wait for lightning weather
2. Engage lightning elemental, the one in the clip is around G-6

## Context (Environment)
It is difficult to reproduce this bug on live because I have to wait for weather effects but I'm logging the issue here for tracking.

**Comment by OmegaBison** [comment] 2019-12-07 06:12
Caused by #27

**Comment by OmegaBison** [comment] 2019-12-07 08:39
Fix has been implemented and will go live with the next patch.

**Closed as completed by OmegaBison** 2019-12-07 08:39 UTC
