### ISSUE TITLE
Bard Maat fight seems broken

### ISSUE THREAD

**Issue by Failgate** [OmegaPrivateServer/issues#120] opened 2020-02-20 16:34 UTC
## Summary
The Bard Maat fight does not appear to be winnable.  Maat was hitting me for around 200 hp a hit.

## Expected Behavior
I'm not sure, I know when I fought him on retail and nasomi on drg he was not even hitting for half that.

## Current Behavior
He is hitting for around a fifth of my total hp at 70.  My defense is at 208, and I had defensive buffs up.

## Possible Solution & Detailed Description
I'm not sure if maybe his damage stat is higher than normal?

## Characters
Hyral

## Steps to Reproduce
1. Get Bard testimony
2. Talk to Maat
3. Fight Maat
4. Die to Maat

## Context
Trying to break the level 70 cap.

**Comment by Failgate** [comment] 2020-02-22 16:46
After looking at a few video's online for Nasomi and Retail, BRD maat was hitting for around 70 hp a hit.

**Comment by OmegaBison** [comment] 2020-02-23 07:54
What gear are you using during melee, and what's your total Defense stat?

**Comment by Failgate** [comment] 2020-02-23 14:28
Defense Stat is at 208 total, Gear is Empress Hairpin, Minstels coat, Lucent Cape, Royal Knights Belt, Custom Hume M Gloves, Bards Cannions, Custom Hume M Boots, 2x Opal rings, 2x Valor Earrings, Justice Badge, Joyeuse, and various instruments for songs.  I had evasion songs on for the fight.

**Comment by dvalderrama89** [comment] 2020-03-27 07:34
Closing this as not a bug. I tested this on my local server using the gear in Failgate's comment plus one additional piece of equipment (which can be obtained at level 40). I was able to beat Maat with one evasion song as described in this ticket, as well as other songs on myself and Maat. I also used a combination of meds and food that are available on the production AH.

**Comment by reddituser7777** [comment] 2020-03-27 07:34
1.

**Closed as completed** 2020-03-27 07:34 UTC
