### ISSUE TITLE
Smoke on the mountain issue. 

### ISSUE THREAD

**Issue by plugin1003** [OmegaPrivateServer/issues#146] opened 2020-03-11 15:05 UTC
## Expected Behavior
 Quest not acting right, supposed to wait 1 earth minute to receive sausage after placing it on fire, waited game day and then some wasn’t able to receive it. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment] 2020-03-29 15:29
Duplicate of 147

**Closed as completed by OmegaBison** 2020-03-29 15:29 UTC
