### ISSUE TITLE
Crabs Big Scissors Pugils Screwdriver Goblins Bomb Toss insane damage

### ISSUE THREAD

**Issue by Craaizy** [OmegaPrivateServer/issues#33] opened 2019-12-10 22:50 UTC
All three of these moves are doing WAY to much damage  currently....dunes parties are getting destroyed by crabs doing 130+ dmg big scissors pugils doing 300+ dmg and bomb toss doing 500+ dmg

## Expected Behavior
what should happens is they should be doing half or 75% less dmg than that.

## Current Behavior
they are basically one shotting dunes party members including tanks

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
Parties are taking huge delays causing leveling to crawl due to multiple deaths.

**Comment by xammy0** [comment] 2019-12-12 18:04
Here are some screenshots from last night, I got hit by screwdriver for 295 dmg, with 107 defense as 21WAR/NIN. Screenshots show 91 defense because I didn't have Protect back on yet while running back to camp. 

![img_20191211_224113](https://user-images.githubusercontent.com/1676239/70737141-db415c80-1cdf-11ea-9ed9-c754ed63f40b.jpg)

![img_20191211_224126](https://user-images.githubusercontent.com/1676239/70737150-df6d7a00-1cdf-11ea-81b3-be7e10b8a287.jpg)

**Comment by dvalderrama89** [comment] 2020-01-21 21:56
I have not seen numbers like the ticket describes when partying with a dedicated tank job and decent gear. This requires more data for us to look into properly. Closing the ticket as `Cannot Reproduce` for now until someone can provide details on what we should be looking for.

**Closed as completed by dvalderrama89** 2020-01-21 21:56 UTC

**Comment by FriskArt** [comment] 2020-03-06 03:09
![screwdriverdunes](https://user-images.githubusercontent.com/55671831/76046472-01b51380-5f2e-11ea-9871-5d20b3ba164c.png)

**Comment by FriskArt** [comment] 2020-03-06 03:10
Dunes PT 16-17, Hit a WHM with Protect up. Shouldnt be doing that much damage.
