### ISSUE TITLE
Bind magic spell does not wear off from magic damage

### ISSUE THREAD

**Issue by whandango1016** [OmegaPrivateServer/issues#20] opened 2019-12-01 03:47 UTC
Bind magic spell does not wear off from magic damage.

## Expected Behavior
When a mob is bound, there should be a very high chance of bind wearing off when hit by any damage.

## Current Behavior
You can bind the mob and cast nukes etc. until it wears off naturally.

## Steps to Reproduce
1. bind a mob
2. repeatedly cast any damaging magic spell on it

**Comment by OmegaBison** [comment] 2019-12-22 02:51
Closing this because I can't reproduce the issue.

What level was the mob in relation to you while you were testing? Low level mobs have a lower chance of being unbound by casts.

**Closed as completed by OmegaBison** 2019-12-22 02:51 UTC
