### ISSUE TITLE
Loot being lost

### ISSUE THREAD

**Issue by Anabeatrizbarros** [OmegaPrivateServer/issues#6] opened 2019-11-24 00:51 UTC
I'm getting an error in which the game says "does not meet the requirements to obtain X item" even when my inventory is not full. The items i lost were silk threads.

## Expected Behavior

I think the items should be going into my inventory.

## Current Behavior

I lose the item instead.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment] 2019-11-25 16:17
Are you using a plugin or addon like LightLuggage to automatically lot/pass or sort inventory?

**Comment by OmegaBison** [comment] 2019-12-04 06:29
Unable to reproduce, and haven't found anybody else with this issue. Closing this ticket.

**Closed as completed by OmegaBison** 2019-12-04 06:29 UTC
